name: dev-the-world
recipe: pantheon
# excludes:
#   - vendor
#   - node_modules
#   - wp-content/plugins/tw-episode-importer/admin/ui/node_modules
env_file:
  - .env
config:
  framework: wordpress
  id: fa3253e3-f798-4bae-a25f-e278d44a9aab
  site: the-world
  php: "7.4"
  via: apache:2.4
  database: mysql
  ssl: false
services:
  node:
    type: node:20
    build:
      - npm install
      - chmod +x scripts/*
  appserver_nginx:
    scanner:
      retry: 10
      okCodes:
        - 302
        - 401
        - 402
        - 403
  edge:
    scanner:
      retry: 10
      okCodes:
        - 302
        - 401
        - 402
        - 403
  edge_ssl:
    scanner:
      retry: 10
      okCodes:
        - 302
        - 401
        - 402
        - 403
  mailhog:
    type: mailhog
    portforward: false
    hogfrom:
      - appserver
tooling:
  wp:
    service: appserver
    cmd: wp --path=/app --url=dev-the-world.lndo.site
  # Lando will run sh scripts but does not recognize the lando command within.
  # local:
  #   service: appserver
  #   description: Find and replace the domain for local environment, and import configuration
  #   cmd:
  #     - './scripts/refresh.sh'
  # refresh:
  #   service: appserver
  #   description: Import database, find and replace the domain for local environment, and import configuration
  #   cmd:
  #     - './scripts/refresh.sh'
  npm:
    service: node
  node:
    service: node
events:
  post-db-import:
    - appserver:
        # Replace Wordpress domain in the database pantheon dev environment
        - wp --path=/app --url=dev-the-world-wp.pantheonsite.io search-replace 'dev-the-world-wp.pantheonsite.io' 'dev-the-world.lndo.site'
